In [1]:
import numpy as np

# NumPy

In [2]:
a = np.array([1,2,9])
a

array([1, 2, 9])

In [3]:
b = np.array([[4.7,5.6],[6.0,7.0]],dtype = 'float32')
b

array([[4.7, 5.6],
       [6. , 7. ]], dtype=float32)

In [4]:
b.ndim

2

In [5]:
b.shape

(2, 2)

In [6]:
a.shape

(3,)

In [7]:
a

array([1, 2, 9])

In [8]:
a.dtype

dtype('int32')

In [9]:
a.itemsize

4

In [10]:
a.size

3

In [11]:
a.nbytes

12

In [12]:
b.itemsize

4

In [13]:
b.dtype

dtype('float32')

In [14]:
b[1,1]

7.0

In [15]:
b.loc[1,1]

AttributeError: 'numpy.ndarray' object has no attribute 'loc'